from typing import Protocol, List, Dict, Optional

class DiscoveryPort(Protocol):
    def get_queries_by_section(self, source_filter: str) -> Dict[str, Dict[str, List[Dict]]]: ...

class FetcherPort(Protocol):
    def __call__(self, query_obj: Dict, **kwargs) -> List[Dict]: ...

class EnrichmentPort(Protocol):
    def __call__(self, raw_data: Dict, section: str, category: str, query_obj: Dict) -> Dict: ...

class QuotaPort(Protocol):
    def can_call(self) -> bool: ...
    def record_call(self) -> None: ...

class CooldownPort(Protocol):
    def should_refetch(self, section: str, cache_key: str, hours: int) -> bool: ...
    def mark_fetched(self, section: str, cache_key: str, category: str, source: str, normalized_query: str) -> None: ...
