from .source_profile_model import SourceProfile

SOURCE_PROFILES: dict[str, SourceProfile] = {
    "rss": SourceProfile(
        content_type="article",
        transport="feed",
        cooldown_hours=0,
        fetch_limit=50,
        requires_scraping=True,
        supports_etag=True,
        supports_last_modified=True,
        freshness_priority="high",
        quality_weight=0.85,
        empty_result_penalty=False,
        expected_media=["image"],
        dedupe_strategy=["canonical_url", "normalized_url", "title_similarity"],
        allowed_sections=["news", "reviews", "tutorials", "trends"],
    ),
    "newsapi": SourceProfile(
        content_type="article",
        transport="api",
        cooldown_hours=0,
        fetch_limit=50,
        requires_scraping=True,
        freshness_priority="very_high",
        quality_weight=0.75,
        empty_result_penalty=True,
        expected_media=["image"],
        dedupe_strategy=["canonical_url", "normalized_url", "title_similarity"],
        allowed_sections=["news", "trends"],
    ),
    "gnews": SourceProfile(
        content_type="article",
        transport="api",
        cooldown_hours=0,
        fetch_limit=50,
        requires_scraping=True,
        freshness_priority="high",
        quality_weight=0.70,
        empty_result_penalty=True,
        expected_media=["image"],
        dedupe_strategy=["canonical_url", "normalized_url", "title_similarity"],
        allowed_sections=["news", "trends"],
    ),
    "youtube": SourceProfile(
        content_type="video",
        transport="api",
        cooldown_hours=0,
        fetch_limit=50,
        quota_cost=100,
        requires_scraping=False,
        freshness_priority="medium",
        quality_weight=0.90,
        expected_media=["thumbnail"],
        dedupe_strategy=["external_id", "normalized_url"],
        allowed_sections=["reviews", "tutorials", "trends", "community"],
    ),
    "reddit": SourceProfile(
        content_type="post",
        transport="api",
        cooldown_hours=0,
        fetch_limit=3,
        quota_cost=1,
        requires_scraping=False,
        freshness_priority="high",
        quality_weight=0.65,
        expected_media=["thumbnail", "image"],
        dedupe_strategy=["external_id", "normalized_url"],
        allowed_sections=["community", "trends", "reviews"],
    ),
}
