"""added content_text, content_html, and word_count columns to Article model

Revision ID: 11cc45b5e9bf
Revises: a352d38fb37d
Create Date: 2026-05-02 00:14:06.661482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11cc45b5e9bf'
down_revision = 'a352d38fb37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['url'])

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quality_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_content_scraped', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('content_source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('content_source')
        batch_op.drop_column('is_content_scraped')
        batch_op.drop_column('quality_score')
        batch_op.drop_column('word_count')
        batch_op.drop_column('content_html')
        batch_op.drop_column('content_text')

    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
