"""add_staged_ingestion_fields

Revision ID: 15777983862f
Revises: 79dd294e296b
Create Date: 2026-05-11 03:20:52.704477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15777983862f'
down_revision = '79dd294e296b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed unnecessary alter_column on article_sources.id

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_enrichment_attempt', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_is_published'), ['is_published'], unique=False)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_videos_is_published'), ['is_published'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_is_published'))
        batch_op.drop_column('is_published')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_is_published'))
        batch_op.drop_column('is_published')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.drop_index(batch_op.f('ix_articles_is_published'))
        batch_op.drop_column('last_enrichment_attempt')
        batch_op.drop_column('is_published')
        batch_op.drop_column('status')

    # Removed unnecessary alter_column on article_sources.id

    # ### end Alembic commands ###
