"""Remove legacy content fields

Revision ID: 16007410e349
Revises: 46102de814d0
Create Date: 2026-07-11 02:06:04.199302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16007410e349'
down_revision = '46102de814d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('content_blocks')
        batch_op.drop_column('content_markdown')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_markdown', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content_blocks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
