"""initial schema

Revision ID: 19fdc5d777e4
Revises: 
Create Date: 2026-04-25 04:25:53.595450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fdc5d777e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'api_name', name='uq_api_usage_date_api')
    )
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_leaf', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_is_leaf'), ['is_leaf'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_created_at'), ['created_at'], unique=False)

    op.create_table('gender_facets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('intent_facets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('last_api_fetch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.String(length=255), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section', 'query_text', name='unique_fetch_per_query')
    )
    with op.batch_alter_table('last_api_fetch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_last_api_fetch_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_last_api_fetch_normalized_query'), ['normalized_query'], unique=False)
        batch_op.create_index(batch_op.f('ix_last_api_fetch_source'), ['source'], unique=False)

    op.create_table('price_tier_facets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_filters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_slug'), ['slug'], unique=True)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_sources_slug'), ['slug'], unique=True)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('website', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('affiliate_network', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('google_id', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(google_id IS NULL AND provider IS NULL) OR (google_id IS NOT NULL AND provider IS NOT NULL)', name='ck_google_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('card_type', sa.TEXT(), nullable=True),
    sa.Column('last_matched_at', sa.DateTime(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('enhanced_query', sa.Text(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('intent_id', sa.Integer(), nullable=True),
    sa.Column('price_tier_id', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['gender_facets.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intent_facets.id'], ),
    sa.ForeignKeyConstraint(['price_tier_id'], ['price_tier_facets.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('idx_article_active', ['is_active'], unique=False)
        batch_op.create_index('idx_article_category_published', ['category_id', 'published_at'], unique=False)
        batch_op.create_index('idx_article_views', ['view_count'], unique=False)
        batch_op.create_index('idx_published_at', ['published_at'], unique=False)
        batch_op.create_index('ix_article_importance', ['importance_score'], unique=False)
        batch_op.create_index('ix_articles_active_published', ['is_active', 'published_at'], unique=False)
        batch_op.create_index('ix_articles_category', ['category_id'], unique=False)
        batch_op.create_index('ix_articles_category_intent_date', ['category_id', 'intent_id', 'published_at'], unique=False)
        batch_op.create_index('ix_articles_gender', ['gender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_importance_score'), ['importance_score'], unique=False)
        batch_op.create_index('ix_articles_intent', ['intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_last_matched_at'), ['last_matched_at'], unique=False)
        batch_op.create_index('ix_articles_price_tier', ['price_tier_id'], unique=False)
        batch_op.create_index('ix_articles_section', ['section_id'], unique=False)
        batch_op.create_index('ix_articles_section_date', ['section_id', 'published_at'], unique=False)

    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('dislikes_count', sa.Integer(), nullable=True),
    sa.CheckConstraint("target_type IN ('article', 'item')", name='ck_comment_target_type'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comments_target', ['target_type', 'target_id'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('card_type', sa.TEXT(), nullable=True),
    sa.Column('searchable_attributes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('ix_items_brand_category', ['brand_id', 'category_id'], unique=False)
        batch_op.create_index('ix_items_category_created', ['category_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_items_slug', ['slug'], unique=False)
        batch_op.create_index('ix_items_type_created', ['item_type', 'created_at'], unique=False)

    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_token', sa.String(length=255), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("target_type IN ('article', 'item', 'comment')", name='ck_reaction_target_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='unique_user_reaction')
    )
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_index('idx_reactions_target', ['target_type', 'target_id'], unique=False)

    op.create_table('saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("target_type IN ('article', 'item')", name='ck_save_target_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_user_save')
    )
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.create_index('ix_save_target', ['target_type', 'target_id'], unique=False)

    op.create_table('user_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("target_type IN ('item', 'article')", name='ck_target_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_user_target')
    )
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.create_index('ix_user_interest_user_target', ['user_id', 'target_type', 'target_id'], unique=False)

    op.create_table('views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("target_type IN ('article', 'item')", name='ck_view_target_type'),
    sa.CheckConstraint('(user_id IS NOT NULL AND ip_address IS NULL) OR (user_id IS NULL AND ip_address IS NOT NULL)', name='ck_view_one_identity'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ip_address', 'target_type', 'target_id', name='unique_view')
    )
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.create_index('idx_views_target', ['target_type', 'target_id'], unique=False)

    op.create_table('article_attributes',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'attribute_id')
    )
    with op.batch_alter_table('article_attributes', schema=None) as batch_op:
        batch_op.create_index('ix_article_attributes_article', ['article_id'], unique=False)
        batch_op.create_index('ix_article_attributes_attribute', ['attribute_id'], unique=False)

    op.create_table('article_brands',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'brand_id')
    )
    with op.batch_alter_table('article_brands', schema=None) as batch_op:
        batch_op.create_index('ix_article_brands_article', ['article_id'], unique=False)
        batch_op.create_index('ix_article_brands_brand', ['brand_id'], unique=False)

    op.create_table('article_items',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'item_id')
    )
    op.create_table('article_sources',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'source_id')
    )
    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.create_index('ix_article_sources_article', ['article_id'], unique=False)
        batch_op.create_index('ix_article_sources_source', ['source_id'], unique=False)

    op.create_table('article_topics',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'topic_id')
    )
    with op.batch_alter_table('article_topics', schema=None) as batch_op:
        batch_op.create_index('ix_article_topics_article', ['article_id'], unique=False)
        batch_op.create_index('ix_article_topics_topic', ['topic_id'], unique=False)

    op.create_table('item_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('spec_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_specifications', schema=None) as batch_op:
        batch_op.create_index('ix_item_specs_item', ['item_id'], unique=False)

    op.create_table('item_topics',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'topic_id')
    )
    with op.batch_alter_table('item_topics', schema=None) as batch_op:
        batch_op.create_index('ix_item_topics_item', ['item_id'], unique=False)
        batch_op.create_index('ix_item_topics_topic', ['topic_id'], unique=False)

    op.create_table('item_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('item_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_variants_price'), ['price'], unique=False)
        batch_op.create_index('ix_variant_default', ['item_id', 'is_default'], unique=False)
        batch_op.create_index('ix_variant_item', ['item_id'], unique=False)

    op.create_table('user_entity_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_interest_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.CheckConstraint('(brand_id IS NOT NULL) OR (category_id IS NOT NULL) OR (topic_id IS NOT NULL)', name='ck_entity_reference'),
    sa.ForeignKeyConstraint(['user_interest_id'], ['user_interests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_entity_interests', schema=None) as batch_op:
        batch_op.create_index('ix_user_entity_interest_ref', ['brand_id', 'category_id', 'topic_id'], unique=False)

    op.create_table('item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['item_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_store_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('external_item_id', sa.String(length=150), nullable=True),
    sa.Column('affiliate_url', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('availability', sa.String(length=32), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['item_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'store_id', name='uq_variant_store')
    )
    with op.batch_alter_table('item_store_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_store_links_availability'), ['availability'], unique=False)
        batch_op.create_index('ix_item_store_price', ['price'], unique=False)
        batch_op.create_index('ix_item_store_store', ['store_id'], unique=False)
        batch_op.create_index('ix_item_store_variant', ['variant_id'], unique=False)

    op.create_table('item_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_store_link_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_store_link_id'], ['item_store_links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_clicks', schema=None) as batch_op:
        batch_op.create_index('ix_item_click_link', ['item_store_link_id'], unique=False)
        batch_op.create_index('ix_item_click_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_clicks_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_clicks_created_at'))
        batch_op.drop_index('ix_item_click_user')
        batch_op.drop_index('ix_item_click_link')

    op.drop_table('item_clicks')
    with op.batch_alter_table('item_store_links', schema=None) as batch_op:
        batch_op.drop_index('ix_item_store_variant')
        batch_op.drop_index('ix_item_store_store')
        batch_op.drop_index('ix_item_store_price')
        batch_op.drop_index(batch_op.f('ix_item_store_links_availability'))

    op.drop_table('item_store_links')
    op.drop_table('item_images')
    with op.batch_alter_table('user_entity_interests', schema=None) as batch_op:
        batch_op.drop_index('ix_user_entity_interest_ref')

    op.drop_table('user_entity_interests')
    with op.batch_alter_table('item_variants', schema=None) as batch_op:
        batch_op.drop_index('ix_variant_item')
        batch_op.drop_index('ix_variant_default')
        batch_op.drop_index(batch_op.f('ix_item_variants_price'))

    op.drop_table('item_variants')
    with op.batch_alter_table('item_topics', schema=None) as batch_op:
        batch_op.drop_index('ix_item_topics_topic')
        batch_op.drop_index('ix_item_topics_item')

    op.drop_table('item_topics')
    with op.batch_alter_table('item_specifications', schema=None) as batch_op:
        batch_op.drop_index('ix_item_specs_item')

    op.drop_table('item_specifications')
    with op.batch_alter_table('article_topics', schema=None) as batch_op:
        batch_op.drop_index('ix_article_topics_topic')
        batch_op.drop_index('ix_article_topics_article')

    op.drop_table('article_topics')
    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_article_sources_source')
        batch_op.drop_index('ix_article_sources_article')

    op.drop_table('article_sources')
    op.drop_table('article_items')
    with op.batch_alter_table('article_brands', schema=None) as batch_op:
        batch_op.drop_index('ix_article_brands_brand')
        batch_op.drop_index('ix_article_brands_article')

    op.drop_table('article_brands')
    with op.batch_alter_table('article_attributes', schema=None) as batch_op:
        batch_op.drop_index('ix_article_attributes_attribute')
        batch_op.drop_index('ix_article_attributes_article')

    op.drop_table('article_attributes')
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.drop_index('idx_views_target')

    op.drop_table('views')
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_index('ix_user_interest_user_target')

    op.drop_table('user_interests')
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.drop_index('ix_save_target')

    op.drop_table('saves')
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index('idx_reactions_target')

    op.drop_table('reactions')
    op.drop_table('newsletter_subscribers')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_type_created')
        batch_op.drop_index('ix_items_slug')
        batch_op.drop_index(batch_op.f('ix_items_created_at'))
        batch_op.drop_index('ix_items_category_created')
        batch_op.drop_index('ix_items_brand_category')

    op.drop_table('items')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('idx_comments_target')

    op.drop_table('comments')
    op.drop_table('attributes')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_section_date')
        batch_op.drop_index('ix_articles_section')
        batch_op.drop_index('ix_articles_price_tier')
        batch_op.drop_index(batch_op.f('ix_articles_last_matched_at'))
        batch_op.drop_index('ix_articles_intent')
        batch_op.drop_index(batch_op.f('ix_articles_importance_score'))
        batch_op.drop_index('ix_articles_gender')
        batch_op.drop_index('ix_articles_category_intent_date')
        batch_op.drop_index('ix_articles_category')
        batch_op.drop_index('ix_articles_active_published')
        batch_op.drop_index('ix_article_importance')
        batch_op.drop_index('idx_published_at')
        batch_op.drop_index('idx_article_views')
        batch_op.drop_index('idx_article_category_published')
        batch_op.drop_index('idx_article_active')

    op.drop_table('articles')
    op.drop_table('users')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_slug'))
        batch_op.drop_index(batch_op.f('ix_topics_normalized_name'))

    op.drop_table('topics')
    op.drop_table('stores')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_slug'))
        batch_op.drop_index(batch_op.f('ix_sources_domain'))

    op.drop_table('sources')
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_slug'))

    op.drop_table('sections')
    op.drop_table('price_tier_facets')
    with op.batch_alter_table('last_api_fetch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_last_api_fetch_source'))
        batch_op.drop_index(batch_op.f('ix_last_api_fetch_normalized_query'))
        batch_op.drop_index(batch_op.f('ix_last_api_fetch_category'))

    op.drop_table('last_api_fetch')
    op.drop_table('intent_facets')
    op.drop_table('gender_facets')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_created_at'))

    op.drop_table('contact_messages')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_categories_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_categories_is_leaf'))

    op.drop_table('categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_slug'))
        batch_op.drop_index(batch_op.f('ix_brands_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_brands_industry'))

    op.drop_table('brands')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
