"""add content status tracking to article model

Revision ID: 1cde9b5a77f2
Revises: 19fdc5d777e4
Create Date: 2026-04-25 16:47:41.645691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cde9b5a77f2'
down_revision = '19fdc5d777e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_content_scraped', sa.Boolean(), nullable=True))
        batch_op.create_index('ix_articles_content_status', ['is_content_scraped', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_content_scraped'), ['is_content_scraped'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_is_content_scraped'))
        batch_op.drop_index('ix_articles_content_status')
        batch_op.drop_column('is_content_scraped')

    # ### end Alembic commands ###
