"""add item search fields

Revision ID: 2189e089e3f8
Revises: bb857a02c484
Create Date: 2026-05-26 03:36:49.400510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2189e089e3f8'
down_revision = 'bb857a02c484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
        batch_op.create_index('ix_items_search_vector', ['search_vector'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_search_vector', postgresql_using='gin')
        batch_op.drop_column('search_vector')
        batch_op.drop_column('search_text')

    # ### end Alembic commands ###
