"""add distribution models

Revision ID: 3b2846397e05
Revises: 9e4884bd1a9c
Create Date: 2026-06-18 19:57:51.487497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2846397e05'
down_revision = '9e4884bd1a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('distribution_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('source_target_type', sa.String(length=50), nullable=False),
    sa.Column('source_target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('platform_specific_text', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('clicks_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.CheckConstraint("source_target_type IN ('content', 'item')", name='ck_distribution_post_target_type'),
    sa.ForeignKeyConstraint(['platform_id'], ['distribution_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distribution_posts', schema=None) as batch_op:
        batch_op.create_index('ix_distribution_post_target', ['source_target_type', 'source_target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_posts_publish_date'), ['publish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_posts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribution_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distribution_posts_status'))
        batch_op.drop_index(batch_op.f('ix_distribution_posts_publish_date'))
        batch_op.drop_index('ix_distribution_post_target')

    op.drop_table('distribution_posts')
    op.drop_table('distribution_platforms')
    # ### end Alembic commands ###
