"""added share and replies count columns to comments

Revision ID: 3c500007b2e0
Revises: ca71272e9a85
Create Date: 2026-06-03 03:55:09.944657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c500007b2e0'
down_revision = 'ca71272e9a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dislike_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('share_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('replies_count', sa.Integer(), nullable=False))
        batch_op.drop_column('dislikes_count')
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dislikes_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('replies_count')
        batch_op.drop_column('share_count')
        batch_op.drop_column('dislike_count')
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###
