"""Add summary field to article

Revision ID: 46102de814d0
Revises: d654f7459ca3
Create Date: 2026-07-10 22:48:54.243336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46102de814d0'
down_revision = 'd654f7459ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
