"""add description_display_rule to Video

Revision ID: 554ad00a3a54
Revises: fa38ab6e0e10
Create Date: 2026-07-07 21:29:04.269673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554ad00a3a54'
down_revision = 'fa38ab6e0e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_display_rule', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('description_display_rule')

    # ### end Alembic commands ###
