"""add published_at to article_sources and rename trust_score

Revision ID: 585bc00eef99
Revises: 2c3395f1ef3d
Create Date: 2026-05-08 04:33:32.811822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585bc00eef99'
down_revision = '2c3395f1ef3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_article_sources_published_at'), ['published_at'], unique=False)

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authority_score', sa.Integer(), nullable=False, server_default="50"))
        batch_op.drop_column('trust_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trust_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('authority_score')

    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_sources_published_at'))
        batch_op.drop_column('published_at')

    # ### end Alembic commands ###
