"""Add new article fields

Revision ID: 5f3dffd548a8
Revises: fb1c28cd9b21
Create Date: 2026-06-30 18:13:23.051014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3dffd548a8'
down_revision = 'fb1c28cd9b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_markdown', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extended_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('extracted_images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('extracted_images')
        batch_op.drop_column('extended_metadata')
        batch_op.drop_column('author')
        batch_op.drop_column('content_markdown')

    # ### end Alembic commands ###
