"""affiliate platform enhancements

Revision ID: 64044543689b
Revises: 4cf6e3e662b2
Create Date: 2026-05-19 01:36:34.108069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64044543689b'
down_revision = '4cf6e3e662b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_store_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('program_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('merchant_category', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('deeplink_generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tracking_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('network_metadata', sa.JSON(), nullable=True))
        batch_op.create_index('ix_item_store_external', ['external_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_store_links_program_name'), ['program_name'], unique=False)
        batch_op.create_index('ix_item_store_program', ['program_name'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_items_source_type'), ['source_type'], unique=False)

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network_slug', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('api_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feed_enabled', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_stores_network_slug'), ['network_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_network_slug'))
        batch_op.drop_column('feed_enabled')
        batch_op.drop_column('api_enabled')
        batch_op.drop_column('network_slug')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_source_type'))
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('source_type')

    with op.batch_alter_table('item_store_links', schema=None) as batch_op:
        batch_op.drop_index('ix_item_store_program')
        batch_op.drop_index(batch_op.f('ix_item_store_links_program_name'))
        batch_op.drop_index('ix_item_store_external')
        batch_op.drop_column('network_metadata')
        batch_op.drop_column('tracking_code')
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('deeplink_generated_at')
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('merchant_category')
        batch_op.drop_column('program_name')
        batch_op.drop_column('original_url')

    # ### end Alembic commands ###
