"""added auth-related fields for User model and removed some fields

Revision ID: 674cdff6ac86
Revises: c650c9e72986
Create Date: 2026-05-30 00:47:55.631703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '674cdff6ac86'
down_revision = 'c650c9e72986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('verification_sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('reset_token')
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('verification_sent_at')
        batch_op.drop_column('verified_at')

    # ### end Alembic commands ###
