"""optimize_article_pipeline_v2

Revision ID: 79dd294e296b
Revises: 8db315f57eb8
Create Date: 2026-05-11 02:14:50.538268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dd294e296b'
down_revision = '8db315f57eb8'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Handle article_sources primary key change
    # Note: We must drop the composite PK before adding the surrogate ID PK
    op.execute("ALTER TABLE article_sources DROP CONSTRAINT article_sources_pkey")
    op.add_column('article_sources', sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False))
    op.create_primary_key("article_sources_pkey", "article_sources", ["id"])

    # 2. Handle articles columns
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('primary_source_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_canonical_url'), ['canonical_url'], unique=False)
        batch_op.create_foreign_key(None, 'article_sources', ['primary_source_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_articles_canonical_url'))
        batch_op.drop_column('primary_source_id')
        batch_op.drop_column('canonical_url')

    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
