"""Add performance indexes

Revision ID: 7a1854a66f2b
Revises: 447f355e8030
Create Date: 2026-04-16 02:28:21.450087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a1854a66f2b'
down_revision = '447f355e8030'
branch_labels = None
depends_on = None


def upgrade():
    # Force higher timeouts for Supabase/Postgres
    op.execute("SET statement_timeout = '120s'")
    op.execute("SET lock_timeout = '60s'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_message_created_at'))

    op.drop_table('contact_message')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('brands_slug_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('categories_slug_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    with op.batch_alter_table('item_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_variants_price'), ['price'], unique=False)

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sections_slug_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_sections_slug'), ['slug'], unique=True)

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('topics_slug_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_topics_slug'), ['slug'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))

    # 2. Fill existing rows
    op.execute("UPDATE users SET is_verified = FALSE")

    # 3. Make it NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified', nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('name')

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_slug'))
        batch_op.create_unique_constraint(batch_op.f('topics_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_slug'))
        batch_op.create_unique_constraint(batch_op.f('sections_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('item_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_variants_price'))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.create_unique_constraint(batch_op.f('categories_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_slug'))
        batch_op.create_unique_constraint(batch_op.f('brands_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    op.create_table('contact_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contact_message_pkey'))
    )
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_message_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_created_at'))

    op.drop_table('contact_messages')
    # ### end Alembic commands ###
