"""convert article_sources to association model

Revision ID: 8db315f57eb8
Revises: 585bc00eef99
Create Date: 2026-05-08 05:14:04.739842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db315f57eb8'
down_revision = '585bc00eef99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_sources_article'))
        batch_op.drop_index(batch_op.f('ix_article_sources_source'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_sources_source'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_sources_article'), ['article_id'], unique=False)

    # ### end Alembic commands ###
