"""Add recommendation_impressions table

Revision ID: 8eae306f6e61
Revises: 3b2846397e05
Create Date: 2026-06-20 04:54:21.218168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8eae306f6e61'
down_revision = '3b2846397e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('context_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_clicks_created_at'), ['created_at'], unique=False)

    op.create_table('recommendation_impressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('context_id', sa.String(length=100), nullable=True),
    sa.Column('entity_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_impressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_impressions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"))

    with op.batch_alter_table('recommendation_impressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_impressions_created_at'))

    op.drop_table('recommendation_impressions')
    with op.batch_alter_table('recommendation_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_clicks_created_at'))

    op.drop_table('recommendation_clicks')
    # ### end Alembic commands ###
