"""add_provider_visibility

Revision ID: 9e4884bd1a9c
Revises: 3c500007b2e0
Create Date: 2026-06-11 22:25:38.882477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4884bd1a9c'
down_revision = '3c500007b2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ingestion_origin', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_contents_ingestion_origin'), ['ingestion_origin'], unique=False)
        batch_op.create_index('ix_contents_source_id', ['source_id'], unique=False)
        batch_op.create_foreign_key(None, 'sources', ['source_id'], ['id'])

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_items_source_id', ['source_id'], unique=False)
        batch_op.create_foreign_key(None, 'sources', ['source_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_items_source_id')
        batch_op.drop_column('source_id')

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_contents_source_id')
        batch_op.drop_index(batch_op.f('ix_contents_ingestion_origin'))
        batch_op.drop_column('ingestion_origin')
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###
