"""added new fields to Post and Video models

Revision ID: a53890296fc5
Revises: b1ace0f088ec
Create Date: 2026-07-03 19:33:01.662126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a53890296fc5'
down_revision = 'b1ace0f088ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime))
        batch_op.add_column(sa.Column('platform_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_posts_subreddit'))
        batch_op.create_index(batch_op.f('ix_posts_community'), ['community'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_posts_platform_community', ['platform', 'community'], unique=False)
        batch_op.create_index('ix_posts_platform_created_at', ['platform', 'created_at'], unique=False)
        batch_op.drop_column('subreddit')

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.DateTime))
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('view_count', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('like_count', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('platform_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_index('ix_videos_platform_creator', ['platform', 'creator'], unique=False)
        batch_op.create_index('ix_videos_platform_published', ['platform', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_published_at'), ['published_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_published_at'))
        batch_op.drop_index('ix_videos_platform_published')
        batch_op.drop_index('ix_videos_platform_creator')
        batch_op.drop_column('platform_metadata')
        batch_op.drop_column('comments_count')
        batch_op.drop_column('like_count')
        batch_op.drop_column('view_count')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('published_at')
        batch_op.drop_column('creator')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subreddit', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_index('ix_posts_platform_created_at')
        batch_op.drop_index('ix_posts_platform_community')
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_posts_community'))
        batch_op.create_index(batch_op.f('ix_posts_subreddit'), ['subreddit'], unique=False)
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('platform_metadata')
        batch_op.drop_column('created_at')
        batch_op.drop_column('url')
        batch_op.drop_column('community')

    # ### end Alembic commands ###
