"""move_is_published_to_base

Revision ID: aa75fff00d25
Revises: 15777983862f
Create Date: 2026-05-11 03:31:12.867917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa75fff00d25'
down_revision = '15777983862f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed unnecessary alter_column on article_sources.id

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_is_published'))
        batch_op.drop_column('is_published')

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contents_is_published'), ['is_published'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_is_published'))
        batch_op.drop_column('is_published')

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_is_published'))
        batch_op.drop_column('is_published')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_videos_is_published'), ['is_published'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_is_published'), ['is_published'], unique=False)

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_is_published'))
        batch_op.drop_column('is_published')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_is_published'), ['is_published'], unique=False)

    # Removed unnecessary alter_column on article_sources.id

    # ### end Alembic commands ###
