"""added body field to Article model

Revision ID: b6ec708c58da
Revises: d692a73729af
Create Date: 2026-07-13 20:26:45.682414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ec708c58da'
down_revision = 'd692a73729af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_topics_slug'))

    op.drop_table('topics')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('body')

    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('normalized_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('topics_pkey'))
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_topics_normalized_name'), ['normalized_name'], unique=False)

    # ### end Alembic commands ###
