"""added etag, last_modified to last_api_fetch

Revision ID: b74722279e15
Revises: aa75fff00d25
Create Date: 2026-05-11 21:53:47.496486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74722279e15'
down_revision = 'aa75fff00d25'
branch_labels = None
depends_on = None


def upgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('article_sources', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)

    with op.batch_alter_table('last_api_fetch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etag', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('last_api_fetch', schema=None) as batch_op:
        batch_op.drop_column('last_modified')
        batch_op.drop_column('etag')

    # with op.batch_alter_table('article_sources', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)

    # ### end Alembic commands ###
