"""add content search fields

Revision ID: bb857a02c484
Revises: ce362789aebf
Create Date: 2026-05-25 22:43:54.761305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb857a02c484'
down_revision = 'ce362789aebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preview_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('search_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
        batch_op.create_index('ix_contents_search_vector', ['search_vector'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_contents_title', ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index('ix_contents_title')
        batch_op.drop_index('ix_contents_search_vector', postgresql_using='gin')
        batch_op.drop_column('search_vector')
        batch_op.drop_column('search_text')
        batch_op.drop_column('preview_text')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
