"""removed item_topics relationship

Revision ID: c650c9e72986
Revises: 2189e089e3f8
Create Date: 2026-05-28 21:50:25.239411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c650c9e72986'
down_revision = '2189e089e3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_topics_item'))
        batch_op.drop_index(batch_op.f('ix_item_topics_topic'))

    op.drop_table('item_topics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_topics',
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('item_topics_item_id_fkey')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('item_topics_topic_id_fkey')),
    sa.PrimaryKeyConstraint('item_id', 'topic_id', name=op.f('item_topics_pkey'))
    )
    with op.batch_alter_table('item_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_topics_topic'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_topics_item'), ['item_id'], unique=False)

    # ### end Alembic commands ###
