"""added reactios and shares count fields to content, item models

Revision ID: ca71272e9a85
Revises: a8c2e4b91d72
Create Date: 2026-06-02 17:50:40.493293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca71272e9a85'
down_revision = 'a8c2e4b91d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('dislike_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('share_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('save_count', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('dislike_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('share_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('save_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('save_count')
        batch_op.drop_column('share_count')
        batch_op.drop_column('dislike_count')
        batch_op.drop_column('like_count')

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_column('save_count')
        batch_op.drop_column('share_count')
        batch_op.drop_column('dislike_count')
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###
