"""removed relationship between Item & Section models

Revision ID: ce362789aebf
Revises: 64044543689b
Create Date: 2026-05-19 02:00:39.820534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce362789aebf'
down_revision = '64044543689b'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('items', schema=None) as batch_op:
#         batch_op.drop_constraint(batch_op.f('items_section_id_fkey'), type_='foreignkey')
#         batch_op.drop_column('section_id')

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('items', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False))
#         batch_op.create_foreign_key(batch_op.f('items_section_id_fkey'), 'sections', ['section_id'], ['id'])

#     # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_section_id_fkey', 'items', type_='foreignkey')
    op.drop_column('items', 'section_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate column
    op.add_column(
        'items',
        sa.Column('section_id', sa.Integer(), nullable=True)
    )

    # Recreate FK
    op.create_foreign_key(
        'items_section_id_fkey',
        'items',
        'sections',
        ['section_id'],
        ['id']
    )
    # ### end Alembic commands ###


