"""newsapi_diffbot_integration

Revision ID: d654f7459ca3
Revises: 554ad00a3a54
Create Date: 2026-07-09 03:13:42.318039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd654f7459ca3'
down_revision = '554ad00a3a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('external_uri', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_external_uri'), ['external_uri'], unique=True)
        batch_op.create_index(batch_op.f('ix_entities_slug'), ['slug'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_uri', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_external_uri'), ['external_uri'], unique=True)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_slug'), ['slug'], unique=True)

    op.create_table('article_categories',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'category_id')
    )
    with op.batch_alter_table('article_categories', schema=None) as batch_op:
        batch_op.create_index('ix_article_categories_article', ['article_id'], unique=False)
        batch_op.create_index('ix_article_categories_category', ['category_id'], unique=False)

    op.create_table('content_entities',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'entity_id')
    )
    op.create_table('content_locations',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'location_id')
    )
    with op.batch_alter_table('content_locations', schema=None) as batch_op:
        batch_op.create_index('ix_content_locations_content', ['content_id'], unique=False)
        batch_op.create_index('ix_content_locations_location', ['location_id'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_uri', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ingestion_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sentiment_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('authors', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('videos', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_external_uri'), ['external_uri'], unique=True)
        batch_op.create_index(batch_op.f('ix_articles_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_sentiment_score'), ['sentiment_score'], unique=False)
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])
        batch_op.drop_column('content_source')
        batch_op.drop_column('body')
        batch_op.drop_column('author')
        batch_op.drop_column('extracted_images')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_uri', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_categories_external_uri'), ['external_uri'], unique=True)

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_uri', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_sources_external_uri'), ['external_uri'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_external_uri'))
        batch_op.drop_column('external_uri')

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_external_uri'))
        batch_op.drop_column('external_uri')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_articles_sentiment_score'))
        batch_op.drop_index(batch_op.f('ix_articles_language'))
        batch_op.drop_index(batch_op.f('ix_articles_external_uri'))
        batch_op.drop_column('event_id')
        batch_op.drop_column('videos')
        batch_op.drop_column('images')
        batch_op.drop_column('authors')
        batch_op.drop_column('sentiment_score')
        batch_op.drop_column('language')
        batch_op.drop_column('ingestion_method')
        batch_op.drop_column('external_uri')

    with op.batch_alter_table('content_locations', schema=None) as batch_op:
        batch_op.drop_index('ix_content_locations_location')
        batch_op.drop_index('ix_content_locations_content')

    op.drop_table('content_locations')
    op.drop_table('content_entities')
    with op.batch_alter_table('article_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_article_categories_category')
        batch_op.drop_index('ix_article_categories_article')

    op.drop_table('article_categories')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_slug'))
        batch_op.drop_index(batch_op.f('ix_locations_country_code'))

    op.drop_table('locations')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_external_uri'))
        batch_op.drop_index(batch_op.f('ix_events_event_date'))

    op.drop_table('events')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_slug'))
        batch_op.drop_index(batch_op.f('ix_entities_external_uri'))
        batch_op.drop_index(batch_op.f('ix_entities_entity_type'))

    op.drop_table('entities')
    # ### end Alembic commands ###
