"""Initial migration

Revision ID: d692a73729af
Revises: 
Create Date: 2026-07-12 02:33:36.092248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd692a73729af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'api_name', name='uq_api_usage_date_api')
    )

    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_uri', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('ingestion_method', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('extended_metadata', sa.JSON(), nullable=True, comment='Raw provider-specific payload for debugging/auditing only. Do NOT use for routing or queries. Structured data (entities, categories, events) belongs in proper relational tables.'),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('videos', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_enrichment_attempt', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('primary_source_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('discovered', 'enriching', 'ready', 'published', 'failed', 'archived')", name='ck_articles_status_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_canonical_url'), ['canonical_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_external_uri'), ['external_uri'], unique=True)
        batch_op.create_index(batch_op.f('ix_articles_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_sentiment_score'), ['sentiment_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)

    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_uri', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_leaf', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_external_uri'), ['external_uri'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_is_leaf'), ['is_leaf'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_created_at'), ['created_at'], unique=False)

    op.create_table('distribution_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('external_uri', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('provider_confidence', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('wikidata_id', sa.String(length=50), nullable=True),
    sa.Column('wikipedia_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_external_uri'), ['external_uri'], unique=True)
        batch_op.create_index(batch_op.f('ix_entities_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_entities_wikidata_id'), ['wikidata_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_uri', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_external_uri'), ['external_uri'], unique=True)

    # Deferred FK: articles.event_id -> events.id (events didn't exist when articles was created)
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_articles_event_id', 'events', ['event_id'], ['id'])

    op.create_table('gender_facets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('intent_facets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('last_api_fetch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.String(length=255), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section', 'query_text', name='unique_fetch_per_query')
    )
    with op.batch_alter_table('last_api_fetch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_last_api_fetch_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_last_api_fetch_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_last_api_fetch_normalized_query'), ['normalized_query'], unique=False)
        batch_op.create_index(batch_op.f('ix_last_api_fetch_source'), ['source'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_slug'), ['slug'], unique=True)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('community', sa.String(length=150), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('platform_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'platform', name='uq_posts_external_platform')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_community'), ['community'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_platform'), ['platform'], unique=False)
        batch_op.create_index('ix_posts_platform_community', ['platform', 'community'], unique=False)
        batch_op.create_index('ix_posts_platform_created_at', ['platform', 'created_at'], unique=False)

    op.create_table('price_tier_facets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_filters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_slug'), ['slug'], unique=True)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_uri', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('authority_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_sources_external_uri'), ['external_uri'], unique=True)
        batch_op.create_index(batch_op.f('ix_sources_slug'), ['slug'], unique=True)

    op.create_table('article_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_sources_published_at'), ['published_at'], unique=False)

    # Add circular FK: articles.primary_source_id -> article_sources.id (deferred until article_sources exists)
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_articles_primary_source_id', 'article_sources', ['primary_source_id'], ['id'])

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('website', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('affiliate_network', sa.String(length=100), nullable=True),
    sa.Column('network_slug', sa.String(length=100), nullable=True),
    sa.Column('api_enabled', sa.Boolean(), nullable=True),
    sa.Column('feed_enabled', sa.Boolean(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_network_slug'), ['network_slug'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('google_id', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(google_id IS NULL AND provider IS NULL) OR (google_id IS NOT NULL AND provider IS NOT NULL)', name='ck_google_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_display_rule', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('channel_name', sa.String(length=150), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('creator', sa.String(length=150), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('platform_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'platform', name='uq_videos_external_platform')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_platform'), ['platform'], unique=False)
        batch_op.create_index('ix_videos_platform_creator', ['platform', 'creator'], unique=False)
        batch_op.create_index('ix_videos_platform_published', ['platform', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_published_at'), ['published_at'], unique=False)

    op.create_table('article_categories',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'category_id')
    )
    with op.batch_alter_table('article_categories', schema=None) as batch_op:
        batch_op.create_index('ix_article_categories_article', ['article_id'], unique=False)
        batch_op.create_index('ix_article_categories_category', ['category_id'], unique=False)

    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('dislike_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('replies_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("target_type IN ('content', 'product')", name='ck_comment_target_type'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('ix_comments_target', ['target_type', 'target_id'], unique=False)

    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('preview_text', sa.Text(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('dislike_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('save_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('review_score', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('intent_id', sa.Integer(), nullable=True),
    sa.Column('price_tier_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('ingestion_origin', sa.String(length=50), nullable=True),
    sa.CheckConstraint("object_type IN ('article', 'video', 'post')", name='ck_contents_object_type_valid'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['gender_facets.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intent_facets.id'], ),
    sa.ForeignKeyConstraint(['price_tier_id'], ['price_tier_facets.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type', 'object_id', name='uq_contents_object_type_id')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index('ix_contents_active', ['is_active'], unique=False)
        batch_op.create_index('ix_contents_active_published_at', ['is_active', 'published_at'], unique=False)
        batch_op.create_index('ix_contents_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_contents_category_intent_published_at', ['category_id', 'intent_id', 'published_at'], unique=False)
        batch_op.create_index('ix_contents_category_published_at', ['category_id', 'published_at'], unique=False)
        batch_op.create_index('ix_contents_gender_id', ['gender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_ingestion_origin'), ['ingestion_origin'], unique=False)
        batch_op.create_index('ix_contents_intent_id', ['intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_object_type'), ['object_type'], unique=False)
        batch_op.create_index('ix_contents_price_tier_id', ['price_tier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_review_count'), ['review_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_review_score'), ['review_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_score'), ['score'], unique=False)
        batch_op.create_index('ix_contents_search_vector', ['search_vector'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_contents_section_id', ['section_id'], unique=False)
        batch_op.create_index('ix_contents_section_published_at', ['section_id', 'published_at'], unique=False)
        batch_op.create_index('ix_contents_source_id', ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_title'), ['title'], unique=False)
        batch_op.create_index('ix_contents_view_count', ['view_count'], unique=False)

    op.create_table('distribution_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('source_target_type', sa.String(length=50), nullable=False),
    sa.Column('source_target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('platform_specific_text', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('clicks_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.CheckConstraint("source_target_type IN ('content', 'product')", name='ck_distribution_post_target_type'),
    sa.ForeignKeyConstraint(['platform_id'], ['distribution_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distribution_posts', schema=None) as batch_op:
        batch_op.create_index('ix_distribution_post_target', ['source_target_type', 'source_target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_posts_publish_date'), ['publish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribution_posts_status'), ['status'], unique=False)

    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_token', sa.String(length=255), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('dislike_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('save_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('searchable_attributes', sa.JSON(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_brand_category', ['brand_id', 'category_id'], unique=False)
        batch_op.create_index('ix_products_category_created', ['category_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_products_search_vector', ['search_vector'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_products_slug', ['slug'], unique=False)
        batch_op.create_index('ix_products_type_created', ['product_type', 'created_at'], unique=False)

    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("target_type IN ('content', 'product', 'comment')", name='ck_reaction_target_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='unique_user_reaction')
    )
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_index('ix_reactions_target', ['target_type', 'target_id'], unique=False)

    op.create_table('recommendation_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('context_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_clicks_created_at'), ['created_at'], unique=False)

    op.create_table('recommendation_impressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('context_id', sa.String(length=100), nullable=True),
    sa.Column('entity_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_impressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_impressions_created_at'), ['created_at'], unique=False)

    op.create_table('saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("target_type IN ('content', 'product')", name='ck_save_target_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', 'collection_name', name='uq_user_save_collection')
    )
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.create_index('ix_save_target', ['target_type', 'target_id'], unique=False)

    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("target_type IN ('content', 'product')", name='ck_share_target_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.create_index('ix_share_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index('ix_share_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('user_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("target_type IN ('product', 'article')", name='ck_target_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_user_target')
    )
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.create_index('ix_user_interest_user_target', ['user_id', 'target_type', 'target_id'], unique=False)

    op.create_table('views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("target_type IN ('content', 'product')", name='ck_view_target_type'),
    sa.CheckConstraint('(user_id IS NOT NULL AND ip_address IS NULL) OR (user_id IS NULL AND ip_address IS NOT NULL)', name='ck_view_one_identity'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ip_address', 'target_type', 'target_id', name='unique_view')
    )
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.create_index('ix_views_target', ['target_type', 'target_id'], unique=False)

    op.create_table('content_attributes',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'attribute_id')
    )
    with op.batch_alter_table('content_attributes', schema=None) as batch_op:
        batch_op.create_index('ix_content_attributes_attribute', ['attribute_id'], unique=False)
        batch_op.create_index('ix_content_attributes_content', ['content_id'], unique=False)

    op.create_table('content_entities',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'entity_id')
    )
    with op.batch_alter_table('content_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_entities_origin'), ['origin'], unique=False)

    op.create_table('content_locations',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'location_id')
    )
    with op.batch_alter_table('content_locations', schema=None) as batch_op:
        batch_op.create_index('ix_content_locations_content', ['content_id'], unique=False)
        batch_op.create_index('ix_content_locations_location', ['location_id'], unique=False)

    op.create_table('content_products',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'product_id')
    )
    with op.batch_alter_table('content_products', schema=None) as batch_op:
        batch_op.create_index('ix_content_products_content', ['content_id'], unique=False)
        batch_op.create_index('ix_content_products_product', ['product_id'], unique=False)

    op.create_table('product_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('spec_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_specifications', schema=None) as batch_op:
        batch_op.create_index('ix_product_specs_product', ['product_id'], unique=False)

    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index('ix_product_variant_default', ['product_id', 'is_default'], unique=False)
        batch_op.create_index('ix_product_variant_product', ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_price'), ['price'], unique=False)

    op.create_table('user_entity_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_interest_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.CheckConstraint('(entity_id IS NOT NULL) OR (category_id IS NOT NULL)', name='ck_entity_reference'),
    sa.ForeignKeyConstraint(['user_interest_id'], ['user_interests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_entity_interests', schema=None) as batch_op:
        batch_op.create_index('ix_user_entity_interest_ref', ['entity_id', 'category_id'], unique=False)

    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_store_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('external_product_id', sa.String(length=150), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('program_name', sa.String(length=100), nullable=True),
    sa.Column('merchant_category', sa.String(length=255), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('deeplink_generated_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('tracking_code', sa.String(length=255), nullable=True),
    sa.Column('network_metadata', sa.JSON(), nullable=True),
    sa.Column('affiliate_url', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('availability', sa.String(length=32), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'store_id', name='uq_product_variant_store')
    )
    with op.batch_alter_table('product_store_links', schema=None) as batch_op:
        batch_op.create_index('ix_product_store_external', ['external_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_store_links_availability'), ['availability'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_store_links_program_name'), ['program_name'], unique=False)
        batch_op.create_index('ix_product_store_price', ['price'], unique=False)
        batch_op.create_index('ix_product_store_program', ['program_name'], unique=False)
        batch_op.create_index('ix_product_store_store', ['store_id'], unique=False)
        batch_op.create_index('ix_product_store_variant', ['variant_id'], unique=False)

    op.create_table('product_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_store_link_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_store_link_id'], ['product_store_links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_clicks', schema=None) as batch_op:
        batch_op.create_index('ix_product_click_link', ['product_store_link_id'], unique=False)
        batch_op.create_index('ix_product_click_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_clicks_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_clicks_created_at'))
        batch_op.drop_index('ix_product_click_user')
        batch_op.drop_index('ix_product_click_link')

    op.drop_table('product_clicks')
    with op.batch_alter_table('product_store_links', schema=None) as batch_op:
        batch_op.drop_index('ix_product_store_variant')
        batch_op.drop_index('ix_product_store_store')
        batch_op.drop_index('ix_product_store_program')
        batch_op.drop_index('ix_product_store_price')
        batch_op.drop_index(batch_op.f('ix_product_store_links_program_name'))
        batch_op.drop_index(batch_op.f('ix_product_store_links_availability'))
        batch_op.drop_index('ix_product_store_external')

    op.drop_table('product_store_links')
    op.drop_table('product_images')
    with op.batch_alter_table('user_entity_interests', schema=None) as batch_op:
        batch_op.drop_index('ix_user_entity_interest_ref')

    op.drop_table('user_entity_interests')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_price'))
        batch_op.drop_index('ix_product_variant_product')
        batch_op.drop_index('ix_product_variant_default')

    op.drop_table('product_variants')
    with op.batch_alter_table('product_specifications', schema=None) as batch_op:
        batch_op.drop_index('ix_product_specs_product')

    op.drop_table('product_specifications')
    with op.batch_alter_table('content_products', schema=None) as batch_op:
        batch_op.drop_index('ix_content_products_product')
        batch_op.drop_index('ix_content_products_content')

    op.drop_table('content_products')
    with op.batch_alter_table('content_locations', schema=None) as batch_op:
        batch_op.drop_index('ix_content_locations_location')
        batch_op.drop_index('ix_content_locations_content')

    op.drop_table('content_locations')
    with op.batch_alter_table('content_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_entities_origin'))

    op.drop_table('content_entities')
    with op.batch_alter_table('content_attributes', schema=None) as batch_op:
        batch_op.drop_index('ix_content_attributes_content')
        batch_op.drop_index('ix_content_attributes_attribute')

    op.drop_table('content_attributes')
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.drop_index('ix_views_target')

    op.drop_table('views')
    with op.batch_alter_table('user_interests', schema=None) as batch_op:
        batch_op.drop_index('ix_user_interest_user_target')

    op.drop_table('user_interests')
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_index('ix_share_user_created')
        batch_op.drop_index('ix_share_target')

    op.drop_table('shares')
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.drop_index('ix_save_target')

    op.drop_table('saves')
    with op.batch_alter_table('recommendation_impressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_impressions_created_at'))

    op.drop_table('recommendation_impressions')
    with op.batch_alter_table('recommendation_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_clicks_created_at'))

    op.drop_table('recommendation_clicks')
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index('ix_reactions_target')

    op.drop_table('reactions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_type_created')
        batch_op.drop_index('ix_products_slug')
        batch_op.drop_index('ix_products_search_vector', postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_products_created_at'))
        batch_op.drop_index('ix_products_category_created')
        batch_op.drop_index('ix_products_brand_category')

    op.drop_table('products')
    op.drop_table('newsletter_subscribers')
    with op.batch_alter_table('distribution_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distribution_posts_status'))
        batch_op.drop_index(batch_op.f('ix_distribution_posts_publish_date'))
        batch_op.drop_index('ix_distribution_post_target')

    op.drop_table('distribution_posts')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index('ix_contents_view_count')
        batch_op.drop_index(batch_op.f('ix_contents_title'))
        batch_op.drop_index('ix_contents_source_id')
        batch_op.drop_index('ix_contents_section_published_at')
        batch_op.drop_index('ix_contents_section_id')
        batch_op.drop_index('ix_contents_search_vector', postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_contents_score'))
        batch_op.drop_index(batch_op.f('ix_contents_review_score'))
        batch_op.drop_index(batch_op.f('ix_contents_review_count'))
        batch_op.drop_index(batch_op.f('ix_contents_published_at'))
        batch_op.drop_index('ix_contents_price_tier_id')
        batch_op.drop_index(batch_op.f('ix_contents_object_type'))
        batch_op.drop_index(batch_op.f('ix_contents_object_id'))
        batch_op.drop_index(batch_op.f('ix_contents_is_published'))
        batch_op.drop_index('ix_contents_intent_id')
        batch_op.drop_index(batch_op.f('ix_contents_ingestion_origin'))
        batch_op.drop_index('ix_contents_gender_id')
        batch_op.drop_index('ix_contents_category_published_at')
        batch_op.drop_index('ix_contents_category_intent_published_at')
        batch_op.drop_index('ix_contents_category_id')
        batch_op.drop_index('ix_contents_active_published_at')
        batch_op.drop_index('ix_contents_active')

    op.drop_table('contents')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('ix_comments_target')

    op.drop_table('comments')
    op.drop_table('attributes')
    with op.batch_alter_table('article_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_article_categories_category')
        batch_op.drop_index('ix_article_categories_article')

    op.drop_table('article_categories')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_published_at'))
        batch_op.drop_index('ix_videos_platform_published')
        batch_op.drop_index('ix_videos_platform_creator')
        batch_op.drop_index(batch_op.f('ix_videos_platform'))

    op.drop_table('videos')
    op.drop_table('users')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_slug'))
        batch_op.drop_index(batch_op.f('ix_topics_normalized_name'))

    op.drop_table('topics')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_network_slug'))

    op.drop_table('stores')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_slug'))
        batch_op.drop_index(batch_op.f('ix_sources_external_uri'))
        batch_op.drop_index(batch_op.f('ix_sources_domain'))

    op.drop_table('sources')
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_slug'))

    op.drop_table('sections')
    op.drop_table('price_tier_facets')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('ix_posts_platform_created_at')
        batch_op.drop_index('ix_posts_platform_community')
        batch_op.drop_index(batch_op.f('ix_posts_platform'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_posts_community'))

    op.drop_table('posts')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_slug'))
        batch_op.drop_index(batch_op.f('ix_locations_country_code'))

    op.drop_table('locations')
    with op.batch_alter_table('last_api_fetch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_last_api_fetch_source'))
        batch_op.drop_index(batch_op.f('ix_last_api_fetch_normalized_query'))
        batch_op.drop_index(batch_op.f('ix_last_api_fetch_is_active'))
        batch_op.drop_index(batch_op.f('ix_last_api_fetch_category'))

    op.drop_table('last_api_fetch')
    op.drop_table('intent_facets')
    op.drop_table('gender_facets')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_external_uri'))
        batch_op.drop_index(batch_op.f('ix_events_event_date'))

    op.drop_table('events')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_wikidata_id'))
        batch_op.drop_index(batch_op.f('ix_entities_slug'))
        batch_op.drop_index(batch_op.f('ix_entities_provider'))
        batch_op.drop_index(batch_op.f('ix_entities_external_uri'))
        batch_op.drop_index(batch_op.f('ix_entities_entity_type'))

    op.drop_table('entities')
    op.drop_table('distribution_platforms')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_created_at'))

    op.drop_table('contact_messages')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_categories_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_categories_is_leaf'))
        batch_op.drop_index(batch_op.f('ix_categories_external_uri'))

    op.drop_table('categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_slug'))
        batch_op.drop_index(batch_op.f('ix_brands_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_brands_industry'))

    op.drop_table('brands')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.drop_index(batch_op.f('ix_articles_sentiment_score'))
        batch_op.drop_index(batch_op.f('ix_articles_language'))
        batch_op.drop_index(batch_op.f('ix_articles_external_uri'))
        batch_op.drop_index(batch_op.f('ix_articles_canonical_url'))

    op.drop_table('articles')
    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_sources_published_at'))

    op.drop_table('article_sources')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
