"""added source health & reliability fields to last_api_fetch

Revision ID: f0bf41510904
Revises: b74722279e15
Create Date: 2026-05-11 23:58:32.093325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bf41510904'
down_revision = 'b74722279e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('last_api_fetch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consecutive_failures', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('success_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_last_api_fetch_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('last_api_fetch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_last_api_fetch_is_active'))
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_error')
        batch_op.drop_column('success_count')
        batch_op.drop_column('consecutive_failures')

    # ### end Alembic commands ###
