"""Add collection_name to Save model

Revision ID: fb1c28cd9b21
Revises: 8eae306f6e61
Create Date: 2026-06-28 17:56:36.284250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1c28cd9b21'
down_revision = '8eae306f6e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_name', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_save'), type_='unique')
        batch_op.create_unique_constraint('uq_user_save_collection', ['user_id', 'target_type', 'target_id', 'collection_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_save_collection', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_save'), ['user_id', 'target_type', 'target_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('collection_name')

    # ### end Alembic commands ###
